region: "us-east-1"
env: "dev"
vpc:
  cidr_block: "10.0.0.0/16"
  subnet:
    public:
      - "10.0.1.0/24"
      - "10.0.3.0/24"
    private:
      - "10.0.2.0/24"
      - "10.0.4.0/24"
  availability_zones:
    - "us-east-1a"
    - "us-east-1b"

eks:
  enabled: true
  name: "dev-sandbox-cluster"
  instance:
    type: "t3.medium"
    scaling:
      desired: 2
      min: 1
      max: 3
tags:
  - key : Environment
    value : "dev"
